# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Release CI

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: 'Step 1: Checkout Code'
      uses: actions/checkout@v2

    - name: 'Step 2: Use Node.js ${{ matrix.node-version }}'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: 'Step 3: Install pnpm'
      run: npm install pnpm -g

    - name: 'Step 4: Install'
      run: pnpm install

    - name: 'Step 5: Build code'
      run: pnpm build:release
